In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Layer, Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from tensorflow.keras.utils import to_categorical

from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.callbacks import EarlyStopping

from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping
import os
from tensorflow.keras.callbacks import TensorBoard

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
cho = pd.read_csv('/content/drive/MyDrive/합친데이터/총_데이터.csv', encoding='cp949')
cho

일자  평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  평균 상대습도(%)         딸기  \
0    20200102       1.3      -2.8       5.3       0.0        76.9   10833.00   
1    20200103       2.0      -1.7       7.7       0.0        73.4   31931.90   
2    20200104       0.6      -3.9       7.7       0.0        78.1   44500.40   
3    20200106       2.9      -0.6       5.0      10.3        87.4   39796.40   
4    20200107       8.6       4.9      14.2      57.0        95.9   26007.50   
..        ...       ...       ...       ...       ...         ...        ...   
926  20221227      -2.3      -8.4       4.9       0.0        67.5  168921.53   
927  20221228      -2.3      -4.9       2.8       0.0        65.6  180503.88   
928  20221229      -3.2      -8.0       2.3       0.0        61.8  179275.02   
929  20221230      -1.1      -3.7       3.2       0.0        67.3  263333.54   
930  20221231      -1.1      -4.8       4.3       0.0        65.8  298105.69   

          메론      방울토마토       수박      참외       토마토   딸기.1  메론.1  방울토마토.1  \
0       48.0   13925.00   3280.0     0.0   12720.0   3880    30   1160.0   
1     5640.0   36123.00   8422.0     0.0   37945.0   3690    20   1020.0   
2     1984.0   31304.00   6480.0     0.0   23518.0   3170    20    940.0   
3     5656.0   40605.00  11167.0     0.0   29405.0   4070    30   1410.0   
4     4928.0   21682.00   3358.0     0.0   24541.0   4510    30   1270.0   
..       ...        ...      ...     ...       ...    ...   ...      ...   
926  17262.4   83013.25  34156.5   430.0  123260.7   6160    30   1210.0   
927  18670.6  118986.25  34806.0   130.0  193487.1   5870    30   1020.0   
928  35472.7  110390.50  30215.0   340.0  101579.0   9340    30   1150.0   
929  29272.0  142674.00  30076.0   670.0  219381.6  14330    30    910.0   
930  22382.6   78615.70  13689.0  1855.0  136890.5  10760    20      NaN   

     수박.1  참외.1  토마토.1 가장많은과일  
0    1170   440   2340  방울토마토  
1     940   390   2080    토마토  
2     850   400   2520     딸기  
3     970   490   3150  방울토마토  
4    1030   490   2940     딸기  
..    ...   ...    ...    ...  
926  1000  1050   2070     딸기  
927   980   790   1990    토마토  
928   890   590   2120     딸기  
929   780   500   1840     딸기  
930   800   480   1790     딸기  

[931 rows x 19 columns]

In [4]:
cho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   일자          931 non-null    int64  
 1   평균기온(°C)    931 non-null    float64
 2   최저기온(°C)    931 non-null    float64
 3   최고기온(°C)    931 non-null    float64
 4   일강수량(mm)    931 non-null    float64
 5   평균 상대습도(%)  931 non-null    float64
 6   딸기          931 non-null    float64
 7   메론          931 non-null    float64
 8   방울토마토       931 non-null    float64
 9   수박          931 non-null    float64
 10  참외          931 non-null    float64
 11  토마토         931 non-null    float64
 12  딸기.1        931 non-null    int64  
 13  메론.1        931 non-null    int64  
 14  방울토마토.1     930 non-null    float64
 15  수박.1        931 non-null    int64  
 16  참외.1        931 non-null    int64  
 17  토마토.1       931 non-null    int64  
 18  가장많은과일      931 non-null    object 
dtypes: float64(12), int64(6), obj

In [5]:
cho=cho.fillna(0)

In [6]:
cho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   일자          931 non-null    int64  
 1   평균기온(°C)    931 non-null    float64
 2   최저기온(°C)    931 non-null    float64
 3   최고기온(°C)    931 non-null    float64
 4   일강수량(mm)    931 non-null    float64
 5   평균 상대습도(%)  931 non-null    float64
 6   딸기          931 non-null    float64
 7   메론          931 non-null    float64
 8   방울토마토       931 non-null    float64
 9   수박          931 non-null    float64
 10  참외          931 non-null    float64
 11  토마토         931 non-null    float64
 12  딸기.1        931 non-null    int64  
 13  메론.1        931 non-null    int64  
 14  방울토마토.1     931 non-null    float64
 15  수박.1        931 non-null    int64  
 16  참외.1        931 non-null    int64  
 17  토마토.1       931 non-null    int64  
 18  가장많은과일      931 non-null    object 
dtypes: float64(12), int64(6), obj

In [7]:
X = cho.iloc[:,1:18]
X

평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  평균 상대습도(%)         딸기       메론  \
0         1.3      -2.8       5.3       0.0        76.9   10833.00     48.0   
1         2.0      -1.7       7.7       0.0        73.4   31931.90   5640.0   
2         0.6      -3.9       7.7       0.0        78.1   44500.40   1984.0   
3         2.9      -0.6       5.0      10.3        87.4   39796.40   5656.0   
4         8.6       4.9      14.2      57.0        95.9   26007.50   4928.0   
..        ...       ...       ...       ...         ...        ...      ...   
926      -2.3      -8.4       4.9       0.0        67.5  168921.53  17262.4   
927      -2.3      -4.9       2.8       0.0        65.6  180503.88  18670.6   
928      -3.2      -8.0       2.3       0.0        61.8  179275.02  35472.7   
929      -1.1      -3.7       3.2       0.0        67.3  263333.54  29272.0   
930      -1.1      -4.8       4.3       0.0        65.8  298105.69  22382.6   

         방울토마토       수박      참외       토마토   딸기.1  메론.1  방울토마토.1  수박.1  참외.1  \
0     13925.00   3280.0     0.0   12720.0   3880    30   1160.0  1170   440   
1     36123.00   8422.0     0.0   37945.0   3690    20   1020.0   940   390   
2     31304.00   6480.0     0.0   23518.0   3170    20    940.0   850   400   
3     40605.00  11167.0     0.0   29405.0   4070    30   1410.0   970   490   
4     21682.00   3358.0     0.0   24541.0   4510    30   1270.0  1030   490   
..         ...      ...     ...       ...    ...   ...      ...   ...   ...   
926   83013.25  34156.5   430.0  123260.7   6160    30   1210.0  1000  1050   
927  118986.25  34806.0   130.0  193487.1   5870    30   1020.0   980   790   
928  110390.50  30215.0   340.0  101579.0   9340    30   1150.0   890   590   
929  142674.00  30076.0   670.0  219381.6  14330    30    910.0   780   500   
930   78615.70  13689.0  1855.0  136890.5  10760    20      0.0   800   480   

     토마토.1  
0     2340  
1     2080  
2     2520  
3     3150  
4     2940  
..     ...  
926   2070  
927   1990  
928   2120  
929   1840  
930   1790  

[931 rows x 17 columns]

In [8]:
# X=X.drop(columns=['딸기','메론','방울토마토','수박','참외','토마토'])

In [9]:
y = cho.iloc[:,18:]
y

가장많은과일
0    방울토마토
1      토마토
2       딸기
3    방울토마토
4       딸기
..     ...
926     딸기
927    토마토
928     딸기
929     딸기
930     딸기

[931 rows x 1 columns]

In [10]:
e = LabelEncoder()
e.fit(y)
y_val = e.transform(y)
print(y_val)

[2 5 0 2 0 2 0 2 0 0 0 2 0 2 0 5 2 2 0 0 0 0 0 0 2 2 0 0 0 0 0 2 0 0 5 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 5 0 0 0 0 0 0 0 5 0 5 0 5
 0 5 0 0 0 5 4 4 4 4 4 5 5 5 4 3 4 5 4 4 4 4 4 3 4 3 3 4 3 3 3 3 3 3 3 3 3
 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 3 3 5 5 5 5 5 5 5 5 5 3 5 5 5 1 1
 1 1 1 1 1 1 1 1 1 1 1 3 3 5 5 5 5 5 5 5 5 5 5 5 5 3 1 5 2 5 5 1 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 2 5 5 2 2 5 5 5 2 2 2 2 2 2 2 2 2 2 0 5
 2 2 2 2 0 2 2 2 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 5 0 5 4 5 5 4 4 5 4 5 4 4 4 0
 0 4 4 3 3 3 4 3 3 3 3 3 4 3 3 4 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [11]:
X

평균기온(°C)  최저기온(°C)  최고기온(°C)  일강수량(mm)  평균 상대습도(%)         딸기       메론  \
0         1.3      -2.8       5.3       0.0        76.9   10833.00     48.0   
1         2.0      -1.7       7.7       0.0        73.4   31931.90   5640.0   
2         0.6      -3.9       7.7       0.0        78.1   44500.40   1984.0   
3         2.9      -0.6       5.0      10.3        87.4   39796.40   5656.0   
4         8.6       4.9      14.2      57.0        95.9   26007.50   4928.0   
..        ...       ...       ...       ...         ...        ...      ...   
926      -2.3      -8.4       4.9       0.0        67.5  168921.53  17262.4   
927      -2.3      -4.9       2.8       0.0        65.6  180503.88  18670.6   
928      -3.2      -8.0       2.3       0.0        61.8  179275.02  35472.7   
929      -1.1      -3.7       3.2       0.0        67.3  263333.54  29272.0   
930      -1.1      -4.8       4.3       0.0        65.8  298105.69  22382.6   

         방울토마토       수박      참외       토마토   딸기.1  메론.1  방울토마토.1  수박.1  참외.1  \
0     13925.00   3280.0     0.0   12720.0   3880    30   1160.0  1170   440   
1     36123.00   8422.0     0.0   37945.0   3690    20   1020.0   940   390   
2     31304.00   6480.0     0.0   23518.0   3170    20    940.0   850   400   
3     40605.00  11167.0     0.0   29405.0   4070    30   1410.0   970   490   
4     21682.00   3358.0     0.0   24541.0   4510    30   1270.0  1030   490   
..         ...      ...     ...       ...    ...   ...      ...   ...   ...   
926   83013.25  34156.5   430.0  123260.7   6160    30   1210.0  1000  1050   
927  118986.25  34806.0   130.0  193487.1   5870    30   1020.0   980   790   
928  110390.50  30215.0   340.0  101579.0   9340    30   1150.0   890   590   
929  142674.00  30076.0   670.0  219381.6  14330    30    910.0   780   500   
930   78615.70  13689.0  1855.0  136890.5  10760    20      0.0   800   480   

     토마토.1  
0     2340  
1     2080  
2     2520  
3     3150  
4     2940  
..     ...  
926   2070  
927   1990  
928   2120  
929   1840  
930   1790  

[931 rows x 17 columns]

In [12]:
y_encoded = tf.keras.utils.to_categorical(y_val)
print(y_encoded)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [13]:
X_train, X_test, y_train,y_test = train_test_split(X,y_encoded, test_size=0.2,random_state=5)

In [14]:
from sklearn.model_selection import StratifiedKFold # 교차검증
n_fold = 10
seed =0
skf = StratifiedKFold(n_fold, shuffle=True,random_state=seed)

In [15]:
X.shape

(931, 17)

In [16]:
from keras.models import Sequential

In [17]:
accuracy =[]
for train, test in skf.split(X,y):
  model = Sequential()
  model.add(Dense(16, input_dim= 17, activation = 'relu'))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(128, activation='relu'))
  model.add(Dense(6, activation ='softmax'))

  model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(X_train,y_train, epochs=200, batch_size=40,validation_data=(X_test,y_test))

  # 모델 예측
  k_accuracy = model.evaluate(X_test,y_test)[1]
  accuracy.append(k_accuracy)

print(accuracy)

Epoch 1/200
19/19 [==============================] - 7s 18ms/step - loss: 4462.8315 - accuracy: 0.5699 - val_loss: 718.2413 - val_accuracy: 0.8075
Epoch 2/200
19/19 [==============================] - 0s 6ms/step - loss: 604.5173 - accuracy: 0.8051 - val_loss: 262.0779 - val_accuracy: 0.8396
Epoch 3/200
19/19 [==============================] - 0s 5ms/step - loss: 268.2725 - accuracy: 0.8414 - val_loss: 458.8423 - val_accuracy: 0.8503
Epoch 4/200
19/19 [==============================] - 0s 6ms/step - loss: 452.4625 - accuracy: 0.8562 - val_loss: 299.0033 - val_accuracy: 0.8289
Epoch 5/200
19/19 [==============================] - 0s 5ms/step - loss: 135.0871 - accuracy: 0.8817 - val_loss: 129.4601 - val_accuracy: 0.8342
Epoch 6/200
19/19 [==============================] - 0s 6ms/step - loss: 89.6932 - accuracy: 0.9032 - val_loss: 138.3599 - val_accuracy: 0.8610
Epoch 7/200
19/19 [==============================] - 0s 6ms/step - loss: 129.5560 - accuracy: 0.8750 - val_loss: 190.3975 - val_a

In [18]:
accuracy =[]
for train, test in skf.split(X,y):
  model = Sequential()
  model.add(Dense(16, input_dim= 17, activation = 'relu'))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(128, activation='relu'))
  model.add(Dense(6, activation ='softmax'))

  model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(X_train,y_train, epochs=200, batch_size=40,validation_data=(X_test,y_test))

  # 모델 예측
  k_accuracy = model.evaluate(X_test,y_test)[1]
  accuracy.append(k_accuracy)

print(accuracy)

Epoch 1/200
19/19 [==============================] - 2s 15ms/step - loss: 4216.8784 - accuracy: 0.6694 - val_loss: 293.3742 - val_accuracy: 0.8824
Epoch 2/200
19/19 [==============================] - 0s 5ms/step - loss: 170.1608 - accuracy: 0.8831 - val_loss: 355.3015 - val_accuracy: 0.8289
Epoch 3/200
19/19 [==============================] - 0s 5ms/step - loss: 127.5347 - accuracy: 0.9099 - val_loss: 139.8177 - val_accuracy: 0.9198
Epoch 4/200
19/19 [==============================] - 0s 5ms/step - loss: 71.0131 - accuracy: 0.9301 - val_loss: 171.8852 - val_accuracy: 0.8556
Epoch 5/200
19/19 [==============================] - 0s 5ms/step - loss: 63.4947 - accuracy: 0.9301 - val_loss: 139.4834 - val_accuracy: 0.9037
Epoch 6/200
19/19 [==============================] - 0s 5ms/step - loss: 69.8903 - accuracy: 0.9355 - val_loss: 70.3501 - val_accuracy: 0.9305
Epoch 7/200
19/19 [==============================] - 0s 5ms/step - loss: 56.2009 - accuracy: 0.9422 - val_loss: 182.8883 - val_accur

In [19]:
X=X.astype('float')

In [20]:
y

가장많은과일
0    방울토마토
1      토마토
2       딸기
3    방울토마토
4       딸기
..     ...
926     딸기
927    토마토
928     딸기
929     딸기
930     딸기

[931 rows x 1 columns]

In [21]:
cho.describe()

일자    평균기온(°C)    최저기온(°C)    최고기온(°C)    일강수량(mm)  \
count  9.310000e+02  931.000000  931.000000  931.000000  931.000000   
mean   2.021066e+07   13.877229    9.132009   19.427605    3.689796   
std    8.181076e+03    9.937846   10.491021    9.709199   12.908069   
min    2.020010e+07  -13.500000  -17.500000   -8.300000    0.000000   
25%    2.020093e+07    6.300000    1.000000   11.900000    0.000000   
50%    2.021070e+07   13.700000    8.300000   20.500000    0.000000   
75%    2.022040e+07   22.700000   18.800000   27.700000    0.450000   
max    2.022123e+07   30.800000   27.700000   36.100000  192.900000   

       평균 상대습도(%)             딸기             메론          방울토마토            수박  \
count  931.000000     931.000000     931.000000     931.000000  9.310000e+02   
mean    68.146831   88214.785285   42280.518045  101581.902685  2.532406e+05   
std     14.833792  126690.735722   52621.447538   64109.197617  3.764227e+05   
min     31.400000       0.000000       0.000000       0.000000  0.000000e+00   
25%     57.800000     168.700000   10617.000000   44437.800000  2.085000e+04   
50%     69.000000   26144.500000   22572.000000   95418.000000  5.016000e+04   
75%     79.000000  129375.450000   57519.250000  137831.850000  3.514792e+05   
max     97.000000  556351.700000  436122.000000  334617.000000  2.012485e+06   

                  참외            토마토          딸기.1        메론.1      방울토마토.1  \
count     931.000000     931.000000    931.000000  931.000000   931.000000   
mean   111336.204726  157365.824533   3583.737916   49.398496  1914.511278   
std    174507.796831  109959.219509   1897.262769   26.962003   666.333292   
min         0.000000       0.000000   1190.000000   20.000000     0.000000   
25%      1010.000000   55915.000000   1890.000000   30.000000  1410.000000   
50%     27983.100000  140554.000000   3140.000000   40.000000  1820.000000   
75%    135288.400000  231820.600000   4935.000000   60.000000  2330.000000   
max    809147.600000  541719.000000  14330.000000  220.000000  5710.000000   

               수박.1         참외.1         토마토.1  
count    931.000000   931.000000    931.000000  
mean    2418.216971  1989.785177   3780.966702  
std     1754.515477  1644.028673   1417.026696  
min      670.000000   320.000000   1280.000000  
25%     1070.000000   510.000000   2775.000000  
50%     1590.000000  1370.000000   3650.000000  
75%     3470.000000  3215.000000   4610.000000  
max    13560.000000  9310.000000  16530.000000

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[ 1.13871395,  1.26625732,  1.01048992, ..., -0.53629672,
        -0.75226124, -0.19013633],
       [ 1.17971493,  1.1598474 ,  1.24175293, ..., -0.6390962 ,
        -0.75826932, -0.58112978],
       [ 0.04193783, -0.2718498 ,  0.35874872, ..., -0.30785343,
         1.14028285,  1.07526065],
       ...,
       [-0.20406803, -0.14609261, -0.06172948, ...,  0.04623367,
         1.44068668,  0.52786982],
       [ 1.36421932,  1.53711896,  1.39943225, ...,  0.51454241,
        -0.60205933,  0.04445974],
       [-0.48082462, -0.66846862, -0.2194088 , ..., -0.84469517,
        -0.968552  , -0.58112978]])

In [24]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(X_train)
train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [25]:
X_train, X_test, y_train,y_test = train_test_split(X,y_val, test_size=0.2,random_state=5)

In [26]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=4)
kn.fit(train_scaled, y_train)

print(kn.score(train_scaled, y_train))
print(kn.score(test_scaled, y_test))

0.9086021505376344
0.8556149732620321


In [27]:
y_test.shape

(187,)

In [28]:
y_pred = kn.predict(X_test)
print(y_pred)

[3 3 3 3 3 3 3 3 3 0 0 0 0 3 0 0 3 3 3 0 1 5 3 3 3 3 0 3 3 3 3 3 3 0 3 3 3
 3 3 3 3 3 0 0 3 3 3 0 3 3 3 3 3 3 3 3 3 0 3 3 3 3 3 0 3 3 3 0 3 3 3 0 0 3
 0 3 3 3 3 5 0 3 3 3 3 3 0 0 3 3 3 3 3 3 3 3 3 0 0 0 3 3 5 3 3 0 3 3 0 1 0
 0 3 3 0 3 0 3 0 3 3 0 3 0 0 3 0 3 0 3 0 3 3 3 3 5 3 3 3 0 3 0 3 0 3 3 3 3
 0 3 0 3 3 1 3 3 1 3 3 3 3 3 3 3 0 0 0 3 3 3 0 0 3 3 5 3 3 0 3 0 3 3 0 3 3
 3 0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [29]:
print(kn.score(X_test, y_test))

0.6844919786096256


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [30]:
y_train

array([5, 5, 5, 3, 2, 5, 0, 3, 3, 0, 5, 3, 5, 3, 3, 3, 3, 3, 0, 0, 3, 1,
       5, 2, 5, 5, 3, 0, 0, 3, 2, 2, 3, 4, 5, 3, 0, 5, 4, 3, 3, 5, 3, 0,
       3, 3, 3, 0, 5, 0, 5, 0, 4, 0, 5, 4, 3, 0, 3, 5, 5, 5, 5, 0, 0, 3,
       3, 3, 3, 3, 3, 3, 0, 5, 3, 5, 3, 3, 3, 0, 5, 3, 3, 0, 3, 3, 1, 3,
       0, 0, 5, 5, 0, 0, 5, 3, 0, 3, 3, 5, 0, 0, 5, 3, 3, 3, 2, 3, 3, 3,
       0, 4, 3, 0, 0, 3, 0, 0, 0, 0, 0, 5, 2, 3, 3, 3, 3, 0, 1, 1, 0, 3,
       3, 5, 0, 5, 0, 5, 0, 0, 3, 0, 5, 2, 1, 3, 5, 3, 0, 3, 0, 5, 0, 5,
       0, 3, 5, 3, 5, 0, 5, 0, 3, 3, 5, 4, 4, 0, 0, 3, 0, 3, 2, 0, 3, 5,
       0, 5, 5, 3, 3, 1, 0, 0, 5, 0, 0, 3, 0, 3, 5, 1, 3, 1, 5, 0, 5, 5,
       5, 5, 1, 3, 1, 3, 0, 0, 5, 0, 0, 5, 0, 5, 0, 0, 3, 1, 3, 5, 3, 2,
       0, 4, 0, 2, 5, 0, 0, 5, 3, 5, 5, 5, 3, 3, 0, 5, 3, 0, 5, 5, 5, 0,
       4, 3, 5, 3, 3, 3, 3, 5, 0, 0, 5, 4, 3, 5, 5, 5, 0, 0, 1, 3, 5, 0,
       0, 0, 5, 3, 0, 5, 5, 0, 3, 0, 0, 5, 5, 3, 4, 5, 0, 3, 3, 5, 3, 3,
       3, 3, 5, 5, 0, 0, 5, 3, 3, 3, 4, 3, 5, 5, 3,

In [31]:
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping
import os
from tensorflow.keras.callbacks import TensorBoard
import time

model_dir = '/content/model/'

if not os.path.exists(model_dir):
  os.mkdir(model_dir)

modelpath = '/content/model/{epoch:02d}-{val_accuracy:.4f}.hdf5'

es = EarlyStopping(monitor='val_loss', mode='min', patience=10)

checkpoint = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True)

tensorboard = TensorBoard(log_dir='logs/{}'.format('열한번째모델'+ str(int(time.time()))))

In [ ]:
model = Sequential()
model.add(Dense(32, input_dim= 11, activation = 'relu'))
model.add(Dense(6, activation ='softmax'))
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train,y_train, epochs=200, batch_size=32,validation_data=(X_test,y_test), callbacks=[tensorboard, es, checkpoint])

In [ ]:


accuracy =[]
for train, test in skf.split(X,y):
  model = Sequential()
  model.add(Dense(16, input_dim= 11, activation = 'relu'))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(128, activation='relu'))
  model.add(Dense(6, activation ='softmax'))

  model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(X_train,y_train, epochs=200, batch_size=40,validation_data=(X_test,y_test))

  # 모델 예측
  k_accuracy = model.evaluate(X_test,y_test)[1]
  accuracy.append(k_accuracy)

print(accuracy)

In [ ]:
accuracy =[]
for train, test in skf.split(X,y):
  model = Sequential()
  model.add(Dense(16, input_dim= 11, activation = 'relu'))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(128, activation='relu'))
  model.add(Dense(6, activation ='softmax'))

  model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(X_train,y_train, epochs=200, batch_size=40,validation_data=(X_test,y_test))

  # 모델 예측
  k_accuracy = model.evaluate(X_test,y_test)[1]
  accuracy.append(k_accuracy)

print(accuracy)

In [ ]:
accuracy =[]
for train, test in skf.split(X,y):
  model = Sequential()
  model.add(Dense(16, input_dim= 11, activation = 'relu'))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(64, activation='relu'))
  model.add(Dense(128, activation='relu'))
  model.add(Dense(6, activation ='softmax'))

  model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])

  model.fit(X_train,y_train, epochs=200, batch_size=40,validation_data=(X_test,y_test))

  # 모델 예측
  k_accuracy = model.evaluate(X_test,y_test)[1]
  accuracy.append(k_accuracy)

print(accuracy)

In [ ]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir logs

In [ ]:
x_test = np.array([
    [3,-5,5,46,34,755,100,433,211,500,53]
])

y_predict = model.predict(x_test)

print(y_predict)

In [ ]:
x_test

In [ ]:
y_predict

In [ ]:
arr = np.array(y_predict)

# 가장 높은 값 위치 찾기
max_index = np.argmax(arr)
print(max_index)
# 결과 배열 생성
result = np.zeros_like(arr)
result[0, max_index] = 1

print(result)

In [ ]:
array_2d = np.array(result)
array_1d = np.reshape(result, -1)


In [ ]:
int_arr=array_1d.astype(int)

In [ ]:
int_arr

In [ ]:
label_encoded = np.argmax(int_arr)

print(label_encoded)


In [ ]:
label = ['딸기','메론','방울토마토','수박','참외','토마토']

x_test = np.array([[15,19,30,15,20,0,0,0,0,0,0]])

y_predict = model.predict(x_test)

arr = np.array(y_predict)

# 가장 높은 값 위치 찾기
max_index = np.argmax(arr)
print(max_index)
# 결과 배열 생성
result = np.zeros_like(arr)
result[0, max_index] = 1

array_2d = np.array(result)
array_1d = np.reshape(result, -1)

int_arr=array_1d.astype(int)
label_encoded = np.argmax(int_arr)

label = label[label_encoded]
print(label)

In [ ]:
label = ['딸기','메론','방울토마토','수박','참외','토마토']
label = label[label_encoded]
print(label)

In [ ]:
label = ['딸기','메론','방울토마토','수박','참외','토마토']

label = label[5]
print(label)

In [ ]:
res=e.inverse_transform(label_encoded)

print(res)

In [ ]:
label_encoded = np.array(label_encoded)

label_decoded = [y_val in label_encoded]

print(label_decoded)

In [ ]:
print("\n Accuracy: %.4f" % model.evaluate(X_test,y_test)[1])

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow import keras
from keras.models import Sequential
from sklearn.preprocessing import LabelEncoder # 문자를 숫자 변환
from tensorflow.keras.layers import Dense

from sklearn.model_selection import train_test_split # 데이터 분리
from sklearn.model_selection import StratifiedKFold # 교차검증

In [ ]:
model.save("fruit_model.h5")

In [ ]:
model = keras.models.load_model('fruit_model.h5')

In [ ]:
model.summary()

In [ ]:
print("\n Accuracy: %.4f" % model.evaluate(X_test,y_test)[1])
print("\n loss: %.4f" % model.evaluate(X_test,y_test)[0])

In [ ]:
history = model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=200, batch_size=200, verbose=0)

In [ ]:
# 검증 셋의 오차값 저장
y_vloss=history.history['val_loss']
# 학습셋의 정확도 trainning  data
y_acc = history.history['accuracy']

# x값 지정 후 정확도를 파란색, 오차를 빨간색으로 표현 할거임
x_len =np.arange(len(y_acc))
plt.plot(x_len,y_vloss,'o', c='red', markersize=13)
plt.plot(x_len,y_acc,'o',c='blue', markersize=13)

plt.show()